# Generated by Django 2.0.3 on 2019-12-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plotter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='Date',
            new_name='Datetime',
        ),
    ]
