# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages_motor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages_motor.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14messages_motor.proto\"9\n\x0cMovingObject\x12\x16\n\x0e\x61nguleVelocity\x18\x05 \x01(\x02\x12\x11\n\tdirection\x18\x06 \x01(\x02\"*\n\nWorldModel\x12\x1c\n\x05motor\x18\x01 \x01(\x0b\x32\r.MovingObjectb\x06proto3'
)




_MOVINGOBJECT = _descriptor.Descriptor(
  name='MovingObject',
  full_name='MovingObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='anguleVelocity', full_name='MovingObject.anguleVelocity', index=0,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='MovingObject.direction', index=1,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=81,
)


_WORLDMODEL = _descriptor.Descriptor(
  name='WorldModel',
  full_name='WorldModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motor', full_name='WorldModel.motor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=125,
)

_WORLDMODEL.fields_by_name['motor'].message_type = _MOVINGOBJECT
DESCRIPTOR.message_types_by_name['MovingObject'] = _MOVINGOBJECT
DESCRIPTOR.message_types_by_name['WorldModel'] = _WORLDMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MovingObject = _reflection.GeneratedProtocolMessageType('MovingObject', (_message.Message,), {
  'DESCRIPTOR' : _MOVINGOBJECT,
  '__module__' : 'messages_motor_pb2'
  # @@protoc_insertion_point(class_scope:MovingObject)
  })
_sym_db.RegisterMessage(MovingObject)

WorldModel = _reflection.GeneratedProtocolMessageType('WorldModel', (_message.Message,), {
  'DESCRIPTOR' : _WORLDMODEL,
  '__module__' : 'messages_motor_pb2'
  # @@protoc_insertion_point(class_scope:WorldModel)
  })
_sym_db.RegisterMessage(WorldModel)


# @@protoc_insertion_point(module_scope)
