# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages_parsian_simurosot_worldmodel.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages_parsian_simurosot_worldmodel.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n+messages_parsian_simurosot_worldmodel.proto\" \n\x08Vector2D\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"\x8d\x01\n\x0cMovingObject\x12\n\n\x02id\x18\x01 \x01(\r\x12\x16\n\x03pos\x18\x02 \x01(\x0b\x32\t.Vector2D\x12\x16\n\x03vel\x18\x03 \x01(\x0b\x32\t.Vector2D\x12\x16\n\x03\x61\x63\x63\x18\x04 \x01(\x0b\x32\t.Vector2D\x12\x16\n\x0e\x61nguleVelocity\x18\x05 \x01(\x02\x12\x11\n\tdirection\x18\x06 \x01(\x02\"\xaa\x01\n\nWorldModel\x12\x1b\n\x04\x62\x61ll\x18\x01 \x01(\x0b\x32\r.MovingObject\x12!\n\nour_robots\x18\x02 \x03(\x0b\x32\r.MovingObject\x12!\n\nopp_robots\x18\x03 \x03(\x0b\x32\r.MovingObject\x12\x0c\n\x04\x62lue\x18\x04 \x01(\x08\x12\x0c\n\x04mode\x18\x05 \x01(\t\x12\x1d\n\tgameState\x18\x06 \x01(\x0e\x32\n.GameState*\x99\x02\n\tGameState\x12\n\n\x06PlayOn\x10\x00\x12\x14\n\x10\x46reeBall_LeftTop\x10\x01\x12\x14\n\x10\x46reeBall_LeftBot\x10\x02\x12\x15\n\x11\x46reeBall_RightTop\x10\x03\x12\x15\n\x11\x46reeBall_RightBot\x10\x04\x12\x14\n\x10PlaceKick_Yellow\x10\x05\x12\x12\n\x0ePlaceKick_Blue\x10\x06\x12\x16\n\x12PenaltyKick_Yellow\x10\x07\x12\x14\n\x10PenaltyKick_Blue\x10\x08\x12\x13\n\x0f\x46reeKick_Yellow\x10\t\x12\x11\n\rFreeKick_Blue\x10\n\x12\x13\n\x0fGoalKick_Yellow\x10\x0b\x12\x11\n\rGoalKick_Blue\x10\x0c\x62\x06proto3'
)

_GAMESTATE = _descriptor.EnumDescriptor(
  name='GameState',
  full_name='GameState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PlayOn', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FreeBall_LeftTop', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FreeBall_LeftBot', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FreeBall_RightTop', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FreeBall_RightBot', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PlaceKick_Yellow', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PlaceKick_Blue', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PenaltyKick_Yellow', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PenaltyKick_Blue', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FreeKick_Yellow', index=9, number=9,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FreeKick_Blue', index=10, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GoalKick_Yellow', index=11, number=11,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GoalKick_Blue', index=12, number=12,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=399,
  serialized_end=680,
)
_sym_db.RegisterEnumDescriptor(_GAMESTATE)

GameState = enum_type_wrapper.EnumTypeWrapper(_GAMESTATE)
PlayOn = 0
FreeBall_LeftTop = 1
FreeBall_LeftBot = 2
FreeBall_RightTop = 3
FreeBall_RightBot = 4
PlaceKick_Yellow = 5
PlaceKick_Blue = 6
PenaltyKick_Yellow = 7
PenaltyKick_Blue = 8
FreeKick_Yellow = 9
FreeKick_Blue = 10
GoalKick_Yellow = 11
GoalKick_Blue = 12



_VECTOR2D = _descriptor.Descriptor(
  name='Vector2D',
  full_name='Vector2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vector2D.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vector2D.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=79,
)


_MOVINGOBJECT = _descriptor.Descriptor(
  name='MovingObject',
  full_name='MovingObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MovingObject.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='MovingObject.pos', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vel', full_name='MovingObject.vel', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acc', full_name='MovingObject.acc', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='anguleVelocity', full_name='MovingObject.anguleVelocity', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='MovingObject.direction', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=223,
)


_WORLDMODEL = _descriptor.Descriptor(
  name='WorldModel',
  full_name='WorldModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ball', full_name='WorldModel.ball', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='our_robots', full_name='WorldModel.our_robots', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='opp_robots', full_name='WorldModel.opp_robots', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='blue', full_name='WorldModel.blue', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='WorldModel.mode', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gameState', full_name='WorldModel.gameState', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=226,
  serialized_end=396,
)

_MOVINGOBJECT.fields_by_name['pos'].message_type = _VECTOR2D
_MOVINGOBJECT.fields_by_name['vel'].message_type = _VECTOR2D
_MOVINGOBJECT.fields_by_name['acc'].message_type = _VECTOR2D
_WORLDMODEL.fields_by_name['ball'].message_type = _MOVINGOBJECT
_WORLDMODEL.fields_by_name['our_robots'].message_type = _MOVINGOBJECT
_WORLDMODEL.fields_by_name['opp_robots'].message_type = _MOVINGOBJECT
_WORLDMODEL.fields_by_name['gameState'].enum_type = _GAMESTATE
DESCRIPTOR.message_types_by_name['Vector2D'] = _VECTOR2D
DESCRIPTOR.message_types_by_name['MovingObject'] = _MOVINGOBJECT
DESCRIPTOR.message_types_by_name['WorldModel'] = _WORLDMODEL
DESCRIPTOR.enum_types_by_name['GameState'] = _GAMESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector2D = _reflection.GeneratedProtocolMessageType('Vector2D', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR2D,
  '__module__' : 'messages_parsian_simurosot_worldmodel_pb2'
  # @@protoc_insertion_point(class_scope:Vector2D)
  })
_sym_db.RegisterMessage(Vector2D)

MovingObject = _reflection.GeneratedProtocolMessageType('MovingObject', (_message.Message,), {
  'DESCRIPTOR' : _MOVINGOBJECT,
  '__module__' : 'messages_parsian_simurosot_worldmodel_pb2'
  # @@protoc_insertion_point(class_scope:MovingObject)
  })
_sym_db.RegisterMessage(MovingObject)

WorldModel = _reflection.GeneratedProtocolMessageType('WorldModel', (_message.Message,), {
  'DESCRIPTOR' : _WORLDMODEL,
  '__module__' : 'messages_parsian_simurosot_worldmodel_pb2'
  # @@protoc_insertion_point(class_scope:WorldModel)
  })
_sym_db.RegisterMessage(WorldModel)


# @@protoc_insertion_point(module_scope)
