# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages_parsian_simurosot_data_wrapper.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import messages_parsian_simurosot_detection_pb2 as messages__parsian__simurosot__detection__pb2
import messages_parsian_simurosot_worldmodel_pb2 as messages__parsian__simurosot__worldmodel__pb2
import messages_parsian_simurosot_debugs_pb2 as messages__parsian__simurosot__debugs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages_parsian_simurosot_data_wrapper.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n-messages_parsian_simurosot_data_wrapper.proto\x1a*messages_parsian_simurosot_detection.proto\x1a+messages_parsian_simurosot_worldmodel.proto\x1a\'messages_parsian_simurosot_debugs.proto\"B\n\x06Header\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\x14\n\x0cstamp_second\x18\x02 \x01(\r\x12\x15\n\rstamp_nsecond\x18\x03 \x01(\r\"\x90\x01\n\x0b\x44\x61taWrapper\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12\x15\n\x05\x64raws\x18\x02 \x01(\x0b\x32\x06.Draws\x12\x15\n\x06\x64\x65\x62ugs\x18\x03 \x01(\x0b\x32\x05.Logs\x12\x19\n\tdetection\x18\x04 \x01(\x0b\x32\x06.Frame\x12\x1f\n\nworldmodel\x18\x05 \x01(\x0b\x32\x0b.WorldModelb\x06proto3'
  ,
  dependencies=[messages__parsian__simurosot__detection__pb2.DESCRIPTOR,messages__parsian__simurosot__worldmodel__pb2.DESCRIPTOR,messages__parsian__simurosot__debugs__pb2.DESCRIPTOR,])




_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq', full_name='Header.seq', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stamp_second', full_name='Header.stamp_second', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stamp_nsecond', full_name='Header.stamp_nsecond', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=179,
  serialized_end=245,
)


_DATAWRAPPER = _descriptor.Descriptor(
  name='DataWrapper',
  full_name='DataWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='DataWrapper.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='draws', full_name='DataWrapper.draws', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='debugs', full_name='DataWrapper.debugs', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detection', full_name='DataWrapper.detection', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='worldmodel', full_name='DataWrapper.worldmodel', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=392,
)

_DATAWRAPPER.fields_by_name['header'].message_type = _HEADER
_DATAWRAPPER.fields_by_name['draws'].message_type = messages__parsian__simurosot__debugs__pb2._DRAWS
_DATAWRAPPER.fields_by_name['debugs'].message_type = messages__parsian__simurosot__debugs__pb2._LOGS
_DATAWRAPPER.fields_by_name['detection'].message_type = messages__parsian__simurosot__detection__pb2._FRAME
_DATAWRAPPER.fields_by_name['worldmodel'].message_type = messages__parsian__simurosot__worldmodel__pb2._WORLDMODEL
DESCRIPTOR.message_types_by_name['Header'] = _HEADER
DESCRIPTOR.message_types_by_name['DataWrapper'] = _DATAWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Header = _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
  'DESCRIPTOR' : _HEADER,
  '__module__' : 'messages_parsian_simurosot_data_wrapper_pb2'
  # @@protoc_insertion_point(class_scope:Header)
  })
_sym_db.RegisterMessage(Header)

DataWrapper = _reflection.GeneratedProtocolMessageType('DataWrapper', (_message.Message,), {
  'DESCRIPTOR' : _DATAWRAPPER,
  '__module__' : 'messages_parsian_simurosot_data_wrapper_pb2'
  # @@protoc_insertion_point(class_scope:DataWrapper)
  })
_sym_db.RegisterMessage(DataWrapper)


# @@protoc_insertion_point(module_scope)
